### ISSUE TITLE
Unclear how to read all frames, or seek

### ISSUE THREAD

**Issue by lostmsu** [hey-red/ImageSharp.AVCodecFormats#2]
Came to this repository from https://github.com/SixLabors/ImageSharp/issues/658

In the test code and any samples only the first frame is extracted.

1. How do I extract subsequent frames? Simply continue calling `Image.Load` on the same stream?
2. Is there a way to seek?

**Comment by hey-red** [comment]
Currently it's is not implemented, but of course possible. 
I think it can be done like gif decoder, with option that decodes first or all frames(maybe possible as lazy?)
https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Metadata/FrameDecodingMode.cs

**Comment by hey-red** [comment]
With latest release it's default behavior.
