### ISSUE TITLE
Native configure

### ISSUE THREAD

**Issue by j4587698** [hey-red/ImageSharp.AVCodecFormats#7]
Hi, can you give me a parameter configuration for ffmpeg configure? I want to compile a arm version, but I can't compile it as small as yours.
Thanks a lot.

**Comment by hey-red** [comment]
https://github.com/hey-red/FFmpeg-Build/blob/master/ffmpeg_build.sh
I have plans to update to FFMpeg 6, but I can't say when it will happen.

**Comment by j4587698** [comment]
Thank you.
